#!/bin/bash
export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

name=$(sed 's/\"//g' <<< $NAME)
if [[ ! $name =~ ^([0-9A-F]{2}[:-]){5}([0-9A-F]{2})$ ]]; then exit 0; fi

action=$(expr "$ACTION" : "\([a-zA-Z]\+\).*")

case "$action" in
add)
    echo $NAME | tr -d '"' > /var/cache/bluetooth/reconnect_device  # Save the mac address of the last connected device (for reconnect after reboot)
    if [[ -z "$BLUETOOTH_SCRIPTS" ]]; then
      python /usr/src/bluetooth-scripts/bluetooth-connect
    fi
    ;;
remove)
	if [[ -z "$BLUETOOTH_SCRIPTS" ]]; then
      python /usr/src/bluetooth-scripts/bluetooth-disconnect
    fi
    ;;
esac
