FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:3-build

ENV DBUS_SYSTEM_BUS_ADDRESS unix:path=/host/run/dbus/system_bus_socket

WORKDIR /usr/src/app

COPY . .
RUN python3 -m pip install --upgrade pip -r config/requirements.txt 
CMD ["bash", "-c", "scripts/run.sh"]
